alias qq="exit"
alias vv="nvim"
alias rr="ranger --choosedir=/tmp/ranger_outdir && cd \$(cat /tmp/ranger_outdir)"
alias ".."="cd .."
alias zz="lazygit"
alias python="python3"
alias vipir="source vipir"
alias ocaml="rlwrap ocaml"
alias fh="\$(cat ~/.bash_history | fzf --tac)"
alias dae="disown & exit"
