alias ".."="cd .."
alias hme="home-manager edit"
alias hms="home-manager switch && nix-collect-garbage -d"
alias ls="ls -A --color=always"
alias ncg="nix-collect-garbage"
alias ncgd="nix-collect-garbage -d"
alias qq="exit"
alias rr="ranger --choosedir=/tmp/ranger_outdir && cd \$(cat /tmp/ranger_outdir)"
alias uu="sudo apt update && sudo apt full-upgrade"
alias vscode="code . & disown & exit"
alias vv="nvim"
alias zz="lazygit"
alias clj="rlwrap clojure"
alias fd="cd \$(tree -indlf | fzf)"
