alias ".."="cd .."
alias ls="ls -A --color=always"
alias qq="exit"
alias rr="ranger --choosedir=/tmp/ranger_outdir && cd \$(cat /tmp/ranger_outdir)"
alias uu="sudo apt update && sudo apt upgrade"
alias vscode="code . & disown & exit"
alias vv="nvim"
alias zz="lazygit"
alias clj="rlwrap clojure"
alias fd="cd \$(tree -indlf | fzf)"
alias bat="batcat"
