alias ".."="cd .."
alias ls="ls -A --color=always"
alias qq="exit"
alias rr="ranger --choosedir=/tmp/ranger_outdir && cd \$(cat /tmp/ranger_outdir)"
alias uu="sudo apt update && sudo apt upgrade"
alias vscode="code . & disown & exit"
alias vv="nvim"
alias zz="lazygit"
alias clj="rlwrap clojure"
alias fd="cd \$(tree -indlf | fzf)"
alias bat="batcat"
alias fbh="FBH=\$(cat ~/.bash_history | fzf) && echo \$FBH && echo && \$FBH"
alias lid="cat \$(tree -ifF | grep -v '/$' | head -n -2) | grep -v ^$ | wc -l"
alias tt="tt.sh"
alias rm="echo 'Use trash cli'"
alias ee="emacsclient -c -a 'emacs'"
alias j-repl="janet -e \"(import spork/netrepl) (netrepl/server)\""
